baseurl       = "/"
title         = "Brain Vitamins"
languageCode  = "en-us"
theme         = "hello-friend-ng"
paginate      = -1
enableGitInfo = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  gitUrl = "https://www.github.com/cqcallaw/www/commit/"

  # Subtitle for home
  homeSubtitle = "food for thought"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "food for thought"
  keywords = "homepage, blog, tech, philosophy"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"

  footerRight = "Theme: modified <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">hello-friend-ng</a>"

  [[params.social]]
    name = "mastodon"
    url = "https://mastodon.xyz/@cqcallaw"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/cqcallaw"

  [[params.social]]
    name = "github"
    url = "https://github.com/cqcallaw"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/cqcallaw"

[taxonomies]
  tag      = "tags"

[languages]
  [languages.en]
    title = "Brain Vitamins"
    # subtitle = "food for thought"
    keywords = "homepage, blog, tech, philosophy"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/blog"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 40
